### ISSUE TITLE
Problem with compiling ifxpy.c

### ISSUE THREAD

**Issue by hzokovic** [OpenInformix/IfxPy#86]
When I run
`python setup.py build`
I got theses errors:
multiple times this one
```
ifxpyc.c: In function ‘_python_IfxPy_free_conn_struct’:
ifxpyc.c:214:34: error: assignment to ‘storeSessionID *’ from incompatible pointer type ‘struct storeSessionID *’ [-Wincompatible-pointer-types]
  214 |                         tempNode = tempNode->next;
      |                                  ^

```

and these two errors as well
```
ifxpyc.c: In function ‘_python_IfxPy_bind_fetch_helper’:
ifxpyc.c:9373:69: error: passing argument 1 of ‘PyBytes_FromStringAndSize’ from incompatible pointer type [-Wincompatible-pointer-types]
 9373 |                                   value = PyBytes_FromStringAndSize(wout_ptr, out_length);
      |                                                                     ^~~~~~~~
      |                                                                     |
      |                                                                     SQLWCHAR * {aka int *}
In file included from /usr/local/include/python3.7m/Python.h:98:
/usr/local/include/python3.7m/bytesobject.h:51:50: note: expected ‘const char *’ but argument is of type ‘SQLWCHAR *’ {aka ‘int *’}
   51 | PyAPI_FUNC(PyObject *) PyBytes_FromStringAndSize(const char *, Py_ssize_t);
      |                                                  ^~~~~~~~~~~~

```
#################
```
ifxpyc.c: In function ‘IfxPy_execute_many’:
ifxpyc.c:11431:52: error: passing argument 4 of ‘SQLDescribeParam’ from incompatible pointer type [-Wincompatible-pointer-types]
11431 |                     (SQLSMALLINT*)(data_type + i), &precision, (SQLSMALLINT*)&scale,
      |                                                    ^~~~~~~~~~
      |                                                    |
      |                                                    SQLUINTEGER * {aka unsigned int *}
In file included from /home/informix/icsdk.4.5.12.12/incl/cli/infxsql.h:1123,
                 from /home/informix/icsdk.4.5.12.12/incl/cli/infxcli.h:33,
                 from ifxpyc.h:41,
                 from ifxpyc.c:43:
/home/informix/icsdk.4.5.12.12/incl/cli/sqlext.h:1832:28: note: expected ‘SQLULEN *’ {aka ‘long long unsigned int *’} but argument is of type ‘SQLUINTEGER *’ {aka ‘unsigned int *’}
 1832 |     SQLULEN               *pcbParamDef,
      |     ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~

```

So this is diff file ifxpy-orig.c and my ifxpy.c which compiles succesfully
```
78c78
< typedef struct storeSessionID {
---
> typedef struct {
9373c9373
<                                   value = PyBytes_FromStringAndSize((const char *)wout_ptr, out_length);
---
>                                   value = PyBytes_FromStringAndSize(wout_ptr, out_length);
11382c11382
<     SQLULEN precision;
---
>     SQLUINTEGER precision;
```

**Comment by jsagrera** [comment]
Thanks for the diff. ;)
I see you are using CSDK 4.50.FC12W12. May I ask which version of Python are you using to compile the module?

**Comment by hzokovic** [comment]
python -V
Python 3.7.17

**Comment by hzokovic** [comment]
when I use
```
python -V
Python 3.13.5
```

I get these errors
```
ifxpyc.c: In function ‘xgetUnicodeDataAsSQLWCHAR’:
ifxpyc.c:2268:27: error: implicit declaration of function ‘PyUnicode_GetSize’; did you mean ‘PyUnicode_Resize’? [-Wimplicit-function-declaration]
 2268 |     Py_ssize_t nCharLen = PyUnicode_GetSize(pyobj);
      |                           ^~~~~~~~~~~~~~~~~
      |                           PyUnicode_Resize
ifxpyc.c:2282:27: error: implicit declaration of function ‘PyUnicode_AS_UNICODE’; did you mean ‘PyUnicode_AsUCS4’? [-Wimplicit-function-declaration]
 2282 |         return (SQLWCHAR*)PyUnicode_AS_UNICODE(pyobj);
      |                           ^~~~~~~~~~~~~~~~~~~~
      |                           PyUnicode_AsUCS4

```

**Comment by jsagrera** [comment]
Thanks, will add the changes asap.
We're also planning to make it work/build with the new CSDK 15.0.x.

**Comment by hzokovic** [comment]
Here is little more diff for Python 3.13.5 compile (it is diff on already modified file):

```
2259c2259
< // Python 3.x compatible
---
> // This function takes value as pyObject and convert it to SQLWCHAR and return it
2262,2264c2262,2282
<     if (!PyUnicode_Check(pyobj)) {
<         PyErr_SetString(PyExc_TypeError, "Expected Unicode object");
<         return NULL;
---
>     PyObject *sysmodule = NULL, *maxuni = NULL;
>     long maxuniValue;
>     PyObject *pyUTFobj;
>     SQLWCHAR* pNewBuffer = NULL;
> #if PY_VERSION_HEX >= 0x03030000
> // For Python 3.3 and above
>     Py_ssize_t nCharLen = PyUnicode_GetSize(pyobj);
> #else
>     // For Python versions below 3.3
>     Py_ssize_t nCharLen = PyUnicode_GET_SIZE(pyobj);
> #endif
> 
> 
>     sysmodule = PyImport_ImportModule("sys");
>     maxuni = PyObject_GetAttrString(sysmodule, "maxunicode");
>     maxuniValue = PyInt_AsLong(maxuni);
> 
>     if (maxuniValue <= 65536)
>     {
>         *isNewBuffer = 0;
>         return (SQLWCHAR*)PyUnicode_AS_UNICODE(pyobj);
2267d2284
<     Py_ssize_t nCharLen = PyUnicode_GetLength(pyobj);
2269,2274c2286
<     
<     SQLWCHAR* pNewBuffer = (SQLWCHAR *)ALLOC_N(SQLWCHAR, nCharLen + 1);
<     if (pNewBuffer == NULL) {
<         PyErr_SetString(PyExc_MemoryError, "Failed to allocate memory");
<         return NULL;
<     }
---
>     pNewBuffer = (SQLWCHAR *)ALLOC_N(SQLWCHAR, nCharLen + 1);
2276,2282c2288,2290
< 
<     // Konvertiraj u UTF-16 (SQLWCHAR je obično uint16_t/wchar_t)
<     PyObject *utf16_obj;
<     if (is_bigendian()) {
<         utf16_obj = PyUnicode_AsEncodedString(pyobj, "utf-16be", "strict");
<     } else {
<         utf16_obj = PyUnicode_AsEncodedString(pyobj, "utf-16le", "strict");
---
>     if (is_bigendian())
>     {
>         pyUTFobj = PyCodec_Encode(pyobj, "utf-16-be", "strict");
2284,2287c2292,2294
<     
<     if (utf16_obj == NULL) {
<         PyMem_Del(pNewBuffer);
<         return NULL;  // Error već postavljen
---
>     else
>     {
>         pyUTFobj = PyCodec_Encode(pyobj, "utf-16-le", "strict");
2289,2293c2296,2297
< 
<     memcpy(pNewBuffer, PyBytes_AS_STRING(utf16_obj), 
<            sizeof(SQLWCHAR) * nCharLen);
<     Py_DECREF(utf16_obj);
<     
---
>     memcpy(pNewBuffer, PyBytes_AsString(pyUTFobj), sizeof(SQLWCHAR) * (nCharLen));
>     Py_DECREF(pyUTFobj);
2294a2299
> 
5735c5740
<                 stmt_size = (int)PyUnicode_GetLength(py_stmt);
---
>                 stmt_size = (int)PyUnicode_GetSize(py_stmt);
6109c6114
<                 curr->ivalue = PyUnicode_GetLength(bind_data);
---
>                 curr->ivalue = PyUnicode_GetSize(bind_data);
11801c11806
<         if (PyUnicode_GetLength(pyprocName) == 0)
---
>         if (StringObj_Size(pyprocName) == 0)

```
